export let strings = {
    russian: {
        home: "Главная",
        projects: "Проекты",
        creators: "Участники",
        about: "О нас",
        contacts: "Контакты",
        englishLocale: "en",
        russianLocale: "ru",
        aboutDescription: "Мы превращаем ваши идеи в реальные проекты",
        aboutParagraph: "Наше дело - это не просто работа." +
            " Мы собрали людей из разных областей творчества и программирования, чтобы вместе воплотить фантазии в жизнь. " +
            "У вас есть идея проекта и вы ищете команду, чтобы реализовать ее? Как раз тут и появляемся мы." +
            " Наша команда создает полноценное визуальное решение и профессианально подходит к разработке каждой стадии проекта." +
            " Мы работаем в области производства цифрового контента - снимаем видео, делаем 3D визуализации и создаем сайты с нуля.",
        loginFormLogin: "Логин",
        loginFormPassword: "Пароль",
        contactsTitle: "КОНТАКТЫ",
        contactsParagraph: "Если у вас есть креативная идея, которую вы хотите реализовать с нашей помощью - то просто оставьте свою" +
            " контактную информацию и описание проекта в форме обратной связи",
        contactsFormName: "Имя",
        contactsFormPhone: "Телефон",
        contactsFormEmail: "Почта",
        contactsFormDescription: "Описание",
        mainTitle: "МЫ ТВОРИМ ДЛЯ ВАС",
        aboutTitle: "О НАС",
        projectsTitle: "ПРОЕКТЫ",
        mainDescription: "Профессиональная работа всей команды",
        contactUs: "Связаться с нами",
        ourProjects: "Наши проекты",
        codeTitle: "Код",
        gamesTitle: "Игры",
        productTitle: "Продукт",
        appsCategory: "Приложения",
        sitesCategory: "Сайты",
        gamesCategory: "Игры",
        filmsCategory: "Фильмы",
        socialVk: "VKontakte",
        socialFacebook: "Facebook",
        socialInstagram: "Instagram",
        validationEmailWrongPattern:"Некорректный адрес почты",
        validationNameRequired: "Поле 'Имя' является обязательным",
        validationLoginRequired: "Поле 'Логин' является обязательным",
        validationPasswordRequired: "Поле 'Пароль' является обязательным",
        validationEmailRequired: "Поле 'Почта' является обязательным",
        validationLoginLength: "Поле 'Логин не может состоять из одного символа'",
        validationPasswordLength: "Пароль не может состоять из одного символа",
        validationNameLength: "Имя не может состоять из одного символа"
    },
    english: {
        home: "Home",
        projects: "Projects",
        creators: "Creators",
        about: "About",
        contacts: "Contacts",
        englishLocale: "en",
        russianLocale: "ru",
        aboutDescription: "We turn your ideas into great projects",
        aboutParagraph: "Your idea is more than a job for us." +
            " We brought people from different areas of art and software engineering to turn your ideas into reality. " +
            "Do you have an idea and look for a team to make it a project? That's when we come in." +
            " Our team creates a comprehensive visualisation and professionally develops every stage of your project." +
            " We work in the field of producing the digital content - shooting videos, making 3D visualisations and creating websites from scratch.",
        loginFormLogin: "Login",
        loginFormPassword: "Password",
        contactsTitle: "CONTACTS",
        contactsParagraph: "If you have a creative idea that you want to realize with our help - " +
            "then you can leave tour data and project description in the feedback form",
        contactsFormName: "Name",
        contactsFormPhone: "Phone",
        contactsFormEmail: "Email",
        contactsFormDescription: "Description",
        mainTitle: "WE CREATE THE IMPOSSIBLE FOR YOU",
        aboutTitle: "ABOUT",
        projectsTitle: "PROJECTS",
        mainDescription: "Quality work of the whole team",
        contactUs: "Contact us",
        ourProjects: "Our projects",
        codeTitle: "Code",
        gamesTitle: "Games",
        productTitle: "Product",
        appsCategory: "Apps",
        sitesCategory: "Sites",
        gamesCategory: "Games",
        filmsCategory: "Films",
        socialVk: "VKontakte",
        socialFacebook: "Facebook",
        socialInstagram: "Instagram",
        validationEmailWrongPattern:"Invalid email address",
        validationNameRequired: "The 'Name' is required",
        validationEmailRequired: "The 'Email' is required",
        validationNameLength: "The name cannot be one character"
    }
}
